# Generated by Django 4.2.5 on 2023-12-20 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_remove_usercredentials_name_userdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercredentials',
            old_name='mobile_number',
            new_name='mob',
        ),
    ]
