# Generated by Django 4.2.5 on 2023-12-20 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_rename_mobile_number_usercredentials_mob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='date_of_birth',
            new_name='dob',
        ),
    ]
