# Generated by Django 4.2.5 on 2023-12-20 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_rename_date_of_birth_userdetails_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercredentials',
            old_name='password',
            new_name='pwd',
        ),
    ]
