# Generated by Django 4.2.5 on 2023-12-20 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_rename_password_usercredentials_pwd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='marital_status',
            new_name='m_s',
        ),
    ]
