# Generated by Django 4.2.5 on 2023-12-20 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_rename_marital_status_userdetails_m_s'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savings', models.CharField(default=0, max_length=100)),
                ('goals', models.TextField()),
                ('user_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='expense.usercredentials')),
            ],
        ),
    ]
