# Generated by Django 4.2.5 on 2023-12-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0007_useraccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
