# Generated by Django 4.2.5 on 2023-12-21 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0010_alter_expense_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='category',
            new_name='pre_category',
        ),
    ]
